WS-004: Sightings Controller
techswitch-learners/whale-spotting-2022-jan pull request #14
Opened 2022-03-24 15:48 UTC by doctone

Methods:
GetAllSightings
GetRecentSighting
Create
Delete

Create and Delete both include Auth.

Can be extended to include Admin at a later stage.

2022-03-24 16:03 UTC, TimLeach635 requested changes
Some comments before it's ready to go!

2022-03-24 16:03 UTC, TimLeach635 commented on backend/Controllers/SightingsController.cs
> +            }
This is _kind of_ better than what you had before, but you still have multiple sources of error in the same `try` block:

`_authService.IsAuthenticated` will throw an error if the username doesn't exist (granted, that would be caught elsewhere), but `_sightingsRepo.Create` will throw an error if it can't create the post. However, you respond to _both_ of these errors by saying "could not create post".

The rule of thumb is that every `try` block should contain _as few lines as possible_, so you can limit them to the exact sources of error. Here, the `IsAuthenticated` and `Create` calls should _not_ be inside the same `try` block - so all you need to do is move one of them outside!

2022-03-24 16:03 UTC, TimLeach635 commented on backend/Controllers/SightingsController.cs
> +            string username = usernamePassword.Split(":")[0];
This code is repeated from above, and it doesn't depend on any external data, so it's the perfect candidate to split out into a helper function! (Yes, I know the code was here already, but that's not an excuse 😉)

2022-03-24 16:03 UTC, TimLeach635 commented on backend/Controllers/SightingsController.cs
> +                    "You are not allowed to delete other people's sightings..."
Ooh, a very atmospheric error message!

2022-03-25 10:15 UTC, chiara-d697 commented on backend/Controllers/SightingsController.cs
> +            }
Removed

2022-03-25 10:15 UTC, chiara-d697 commented on backend/Controllers/SightingsController.cs
> +            }
Removed

2022-03-25 10:30 UTC, chiara-d697 commented on backend/Controllers/SightingsController.cs
> +            }
Code reformulated

2022-03-25 14:00 UTC, TimLeach635 reviewed
One tiny comment!

2022-03-25 14:00 UTC, TimLeach635 commented on backend/Controllers/SightingsController.cs
> +                    "Please login if you would like to report a sighting"
This is what you do when the `GetByUsername` method fails, right? So why is that a 403, and why this explanation? I think this would be a 401 Unauthenticated, since they haven't provided valid authentication information and we can't authenticate them, and the message could be more descriptive (e.g. "The given username is not valid")

2022-03-25 14:00 UTC, TimLeach635 commented on backend/Controllers/SightingsController.cs
> +                return Created("/", newSighting);
Good!

2022-03-25 14:10 UTC, chiara-d697 commented on backend/Controllers/SightingsController.cs
> +                    "Please login if you would like to report a sighting"
Change made

2022-03-25 14:14 UTC, merged