WS-027: Leaderboard Component
techswitch-learners/whale-spotting-2022-jan pull request #41
Opened 2022-04-04 10:04 UTC by chiara-d697

![image](https://user-images.githubusercontent.com/74209737/161521753-dc20fc6e-053b-4f1b-aacc-f67fe0d39cf6.png)

Leaderboard component created from LINQ join query and react table

2022-04-05 02:24 UTC, AndrewYHuang requested changes

2022-04-05 02:24 UTC, AndrewYHuang commented on backend/Repositories/UsersRepo.cs
> +using  WhaleSpotting.Models.Response;
Whitespace

2022-04-05 02:24 UTC, AndrewYHuang commented on backend/Repositories/UsersRepo.cs
> +
Extra whitespace

2022-04-05 02:24 UTC, AndrewYHuang commented on backend/Repositories/UsersRepo.cs
> +
Extra whitespace

2022-04-05 02:24 UTC, AndrewYHuang commented on backend/Repositories/UsersRepo.cs
> +            new{username = user.Username, count = sighting.count});
I think we want some different indentation here

2022-04-05 02:24 UTC, AndrewYHuang commented on backend/Repositories/UsersRepo.cs
> +            new{username = user.Username, count = sighting.count});
Maybe something like
```suggestion
            return _context.Sightings
                .GroupBy(sighting => sighting.CreatedByUserId)
                .Select(sighting => new {count = sighting.Count(), userId = sighting.Key})
                .OrderByDescending(g => g.count)
                .Join(
                    _context.Users, 
                    sighting => sighting.userId, 
                    user => user.Id, 
                    (sighting, user) => new LeaderboardEntry { 
                        Username = user.Username, 
                        Count = sighting.count 
                    }
                ).ToList();
```

This way we can also remove quite a lot of the code below as we are returning a list of LeaderboardEntries

2022-04-05 09:29 UTC, chiara-d697 commented on backend/Repositories/UsersRepo.cs
> +            new{username = user.Username, count = sighting.count});
Refactored as suggested

2022-04-05 09:29 UTC, chiara-d697 commented on backend/Repositories/UsersRepo.cs
> +using  WhaleSpotting.Models.Response;
Removed line

2022-04-05 09:39 UTC, chiara-d697 commented
Implemented the above fixes and resolved merge conflicts

2022-04-07 09:19 UTC, TimLeach635 approved these changes
Looks good to me!

2022-04-07 10:08 UTC, merged