WS-035: Pagination on All Sightings Page
techswitch-learners/whale-spotting-2022-jan pull request #43
Opened 2022-04-04 13:59 UTC by zuhalkurt

![image](https://user-images.githubusercontent.com/79058038/161560146-844cd09b-e7c1-4b95-9743-ffcbab65fbfc.png)

![image](https://user-images.githubusercontent.com/79058038/161560204-d43f03c5-1a1a-4d7c-a87d-58ee4f8b6d46.png)

2022-04-05 02:29 UTC, AndrewYHuang requested changes

2022-04-05 02:29 UTC, AndrewYHuang commented on frontend/tsconfig.json
> +    "noImplicitAny": false
Why are we disabling checking for implicit 'any's? Are you encountering a type error somewhere?

2022-04-05 08:44 UTC, zuhalkurt commented on frontend/tsconfig.json
> +    "noImplicitAny": false
Yes, we had a type error in handlePageClick function. We googled it and it was the most common answer for the error :)

2022-04-05 11:25 UTC, AndrewYHuang commented on frontend/tsconfig.json
> +    "noImplicitAny": false
Ah, okay! :) Ideally we wouldn't disable this sort of checking because it makes the type checking in TypeScript a bit less useful and safe. Ae there any alternative ways of solving the type error? What was the exact error?

2022-04-06 08:28 UTC, zuhalkurt commented on frontend/tsconfig.json
> +    "noImplicitAny": false
It was coming from function handlePageClick({ selected: selectedPage }) {
    setCurrentPage(selectedPage);
  } this part of the code. It wasn't happy with ({ selected: selectedPage }) this bit.

2022-04-07 11:15 UTC, TimLeach635 requested changes
Only a few small changes!

2022-04-07 11:15 UTC, TimLeach635 commented on frontend/src/pages/Sightings/SightingListPage.scss
> +.previousLabel {
Casing for CSS classes should be `next-label` and `previous-label`

2022-04-07 11:15 UTC, TimLeach635 commented on package-lock.json
> +}
I think you ran `npm install` in the root directory by mistake! Please delete this file 😊

2022-04-08 09:59 UTC, TimLeach635 approved these changes

2022-04-08 10:20 UTC, merged