WS-034: External API data
techswitch-learners/whale-spotting-2022-jan pull request #46
Opened 2022-04-06 14:02 UTC by rachelledupuis

Combine external API data with local database into one array which sorts all sightings by date.
![image](https://user-images.githubusercontent.com/96778431/161992642-f71ba21b-33d0-47b8-a4ce-71462cf36e06.png)

2022-04-06 15:31 UTC, TimLeach635 requested changes
Looking really, really good! Some excellent code here, just a few changes!

2022-04-06 15:31 UTC, TimLeach635 commented on frontend/src/clients/apiClients.ts
> +} */
Remove comments please!

2022-04-06 15:31 UTC, TimLeach635 commented on frontend/src/clients/apiClients.ts
> +export async function GetExternalSightings(): Promise<Array<ExternalSighting>> {
Name lowercase: `getExternalSightings()`

2022-04-06 15:31 UTC, TimLeach635 commented on frontend/src/pages/Sightings/SightingListPage.tsx
> +            .reverse()
Also, why are you casting to a string and then immediately parsing? `toString()` and `parse()` are opposites of each other, it's like calling `date.toString().toDate()`

2022-04-06 15:31 UTC, TimLeach635 commented on frontend/src/pages/Sightings/SightingListPage.tsx
> +  }
This is good for now, but what happens if you have an actual empty list coming back from the backends?

2022-04-06 17:22 UTC, rachelledupuis commented on frontend/src/clients/apiClients.ts
> +} */
Removed

2022-04-06 17:24 UTC, rachelledupuis commented on frontend/src/clients/apiClients.ts
> +} */
Removed

2022-04-06 17:26 UTC, rachelledupuis commented on frontend/src/clients/apiClients.ts
> +export async function GetExternalSightings(): Promise<Array<ExternalSighting>> {
Done

2022-04-06 18:08 UTC, rachelledupuis commented on frontend/src/pages/Sightings/SightingListPage.tsx
> +            .reverse()
Removed reverse(), parse(), and toString()

2022-04-07 09:50 UTC, rachelledupuis commented on frontend/src/components/SightingListPage/Sighting/ExternalApiSighting.tsx
> +  i,
Renamed to sighting and index

2022-04-07 09:55 UTC, rachelledupuis commented on frontend/src/components/SightingListPage/Sighting/ExternalApiSighting.tsx
> +          {s.species[0].name} ({s.species[0].latinName})
The external API returns an array of species. We are assuming there will be only 1 species per sighting based on the 1 sighting in the external API/how we've set up our database.

![image](https://user-images.githubusercontent.com/96778431/162173154-47145198-03ff-4f99-a3dc-67e97987bc59.png)

2022-04-07 11:04 UTC, rachelledupuis commented on frontend/src/components/SightingListPage/Sighting/ExternalApiSighting.tsx
> +          <p>Confirmed ☑</p>
Changed to "Worldwide"

2022-04-07 11:13 UTC, rachelledupuis commented on frontend/src/components/SightingListPage/SightingList/SightingList.tsx
> +  combined,
Renamed to combinedSightingList

2022-04-07 11:14 UTC, rachelledupuis commented on frontend/src/components/SightingListPage/SightingList/SightingList.tsx
> +  deleteWhaleSighting,
Moved these functions to newly created AdminButtons component, so these functions are used there and no longer passed as props.

2022-04-07 11:14 UTC, rachelledupuis commented on frontend/src/pages/Sightings/SightingListPage.tsx
> +  const [combined, setCombined] = useState<Array<Sighting | ExternalSighting>>(
Done

2022-04-07 11:36 UTC, rachelledupuis commented on frontend/src/pages/Sightings/SightingListPage.tsx
> +  }
Put loading in state so that it only displays loading if set to true. Changed message for combined.length === 0 to make it clear there are no sightings to display.

2022-04-07 13:39 UTC, rachelledupuis commented on frontend/src/components/SightingListPage/Sighting/InternalSighting.tsx
> +            </div>
Created separate components for confirm and delete buttons

2022-04-08 10:18 UTC, TimLeach635 requested changes
A few more comments!

2022-04-08 10:18 UTC, TimLeach635 commented on frontend/src/components/SightingListPage/Sighting/InternalSighting.tsx
> +  >;
Remove

2022-04-08 10:18 UTC, TimLeach635 commented on frontend/src/components/SightingListPage/Sighting/InternalSighting.tsx
> +  const [actionOnDelete, setActionOnDelete] = useState<boolean>(false);
Rename to something like `isConfirmed` and `isDeleted`

2022-04-08 10:18 UTC, TimLeach635 commented on frontend/src/components/SightingListPage/SightingList/SightingList.tsx
> +              setCombinedSightingList={setCombinedSightingList}
I'm not sure you need to pass this prop down at all anymore!

2022-04-08 10:18 UTC, TimLeach635 commented on frontend/src/pages/Sightings/SightingListPage.scss
> +.sighting__list__loading {
"loading" is a modifier (I think), so CSS BEM naming convention would suggest `.sighting__list--loading`

2022-04-08 10:18 UTC, TimLeach635 commented on frontend/src/pages/Sightings/SightingListPage.tsx
> +      <h1 className="sighting__list__loading">
Why is it still using the "loading" CSS class if it has finished loading?

2022-04-08 10:51 UTC, doctone commented on frontend/src/components/SightingListPage/Sighting/InternalSighting.tsx
> +  >;
Removed

2022-04-08 10:54 UTC, doctone commented on frontend/src/components/SightingListPage/Sighting/InternalSighting.tsx
> +  const [actionOnDelete, setActionOnDelete] = useState<boolean>(false);
Renamed

2022-04-08 10:55 UTC, doctone commented on frontend/src/components/SightingListPage/SightingList/SightingList.tsx
> +              setCombinedSightingList={setCombinedSightingList}
Removed

2022-04-08 10:56 UTC, doctone commented on frontend/src/pages/Sightings/SightingListPage.scss
> +.sighting__list__loading {
Renamed

2022-04-08 11:02 UTC, doctone commented on frontend/src/pages/Sightings/SightingListPage.tsx
> +      <h1 className="sighting__list__loading">
Renamed

2022-04-08 12:41 UTC, TimLeach635 requested changes
Just one comment!

2022-04-08 12:41 UTC, TimLeach635 commented on frontend/src/components/SightingListPage/Sighting/InternalSighting.tsx
> +  if (isDeleted)
Shouldn't this be the negative? `!isDeleted`?

2022-04-08 12:47 UTC, doctone commented on frontend/src/components/SightingListPage/Sighting/InternalSighting.tsx
> +  if (isDeleted)
I think it's correct because if `isDeleted` is true then we want to render a div that shows the post has been deleted, otherwise render the whale sighting as normal?

`if (isDeleted)
![image](https://user-images.githubusercontent.com/70722177/162438411-92557515-51fe-4704-8046-ce7c077341d6.png)

otherwise return
![image](https://user-images.githubusercontent.com/70722177/162438515-9bd7b33d-d9ed-4cd9-a00a-1fa5f665364c.png)

2022-04-08 12:58 UTC, TimLeach635 approved these changes

2022-04-08 13:29 UTC, merged