WS-041: Admin locations endpoints WIP
techswitch-learners/whale-spotting-2022-jan pull request #47
Opened 2022-04-06 14:49 UTC by chiara-d697

Create and Delete location endpoints have restricted access so only admins can delete or create a location. 
Update is not working but we have submitted this review as a draft so you can take a look.

2022-04-07 11:33 UTC, chiara-d697 commented
Update now working

2022-04-08 09:36 UTC, TimLeach635 requested changes
Nice, just a few changes!

2022-04-08 09:36 UTC, TimLeach635 commented on backend/Controllers/LocationController.cs
> +            if (user.Role == 0)
Better to check that they're _not_ an admin - what if we add a new role that still shouldn't be able to add locations? A "guest", maybe? By default, they would be able to access this endpoint!

2022-04-08 09:36 UTC, TimLeach635 commented on backend/Controllers/LocationController.cs
> +
Whitespace!

2022-04-08 09:36 UTC, TimLeach635 commented on backend/Controllers/LocationController.cs
> +            if (user.Role == 0)
Likewise here from above

2022-04-08 09:36 UTC, TimLeach635 commented on backend/Controllers/LocationController.cs
> +            if (user.Role == 0)
ditto

2022-04-08 09:36 UTC, TimLeach635 commented on backend/Models/Request/UpdateLocationRequest.cs
> +        }
Don't change this, but you will never need this constructor - `UpdateLocationRequest` is parsed from HTTP requests sent to this API, so our code will only ever be converting _from_ this class, never to!

2022-04-08 09:52 UTC, DeepashriDali commented on backend/Controllers/LocationController.cs
> +            if (user.Role == 0)
Changed code to reflect not admin.

2022-04-08 09:53 UTC, DeepashriDali commented on backend/Controllers/LocationController.cs
> +
Removed whitespace

2022-04-08 09:55 UTC, DeepashriDali commented on backend/Models/Request/UpdateLocationRequest.cs
> +        }
Left this in

2022-04-08 12:43 UTC, TimLeach635 approved these changes

2022-04-08 12:44 UTC, merged