WS-010: Login page
techswitch-learners/whale-spotting-2022-jan pull request #8
Opened 2022-03-23 15:31 UTC by chiara-d697

Connect the login page to the backend, so that users can log in if their information is in the database.
![image](https://user-images.githubusercontent.com/74209737/159736260-e468d80c-a2c0-459b-ae8f-484b2301f6d9.png)

2022-03-23 15:37 UTC, TimLeach635 requested changes
Nice! Just some comments for you

2022-03-23 15:37 UTC, TimLeach635 commented on frontend/src/App.tsx
> +      <Route path="/home" component={Home}/>
Why have you changed the path? I think `/` should always take you to the homepage, no?

2022-03-23 15:37 UTC, TimLeach635 commented on frontend/src/App.tsx
> +
Have you run `npm install`? I would expect the formatter to have removed these lines, but it seems like it hasn't run for you

2022-03-23 15:37 UTC, TimLeach635 commented on frontend/src/components/login/Login.scss
> +.login, form {
You've decided to format _all forms_ in the whole site this way! Was that on purpose?

2022-03-23 15:37 UTC, TimLeach635 commented on frontend/src/components/login/Login.scss
> +input {
Likewise here - have you meant to assert that _every input element on the whole site_ should have a `2em` margin?

2022-03-24 10:22 UTC, doctone commented
In our App.tsx file, we had to change the order of the routes in order to see the login page when we click the nav link:
![image](https://user-images.githubusercontent.com/70722177/159895634-0abea5a7-a7b3-47ee-8cc3-5b199c2ccbb4.png)

We're not quite sure why this is working, and whether it means our solution is correct or just 'hacked' ?!?!

2022-03-24 13:51 UTC, TimLeach635 approved these changes

2022-03-24 13:51 UTC, merged